default_platform(:ios)
Dir[File.expand_path('Fastfiles/*.rb', __dir__)].each { |f| import f }

lane :hello do
  # UI.success "✅ Hello World!"
  # haha
  # ensure_git_status_clean_pwd(path: '/Users/xiongzenghui/collect_fastlane/toolbox')
  # puts read_podspec(file_path: '/Users/xiongzenghui/Desktop/ZHCoreNetwork/ZHCoreNetwork.podspec')
  # puts git_tag_exist(
  #   repo: '/Users/xiongzenghui/Desktop/xzhworkspace',
  #   tag: '1.0.0'
  # )
  # git_tag_add_push(
  #   repo: '/Users/xiongzenghui/Desktop/xzhworkspace',
  #   tag: '1.1.1',
  #   branch: 'master',
  #   commit_message: 'v1.1.1'
  # )
end
